version: "3.9"

services:
  db-microservice-infra-boilerplate:
    image: postgres:15-alpine
    container_name: db-microservice-infra-boilerplate
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-microservice-infra-boilerplate_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api-microservice-infra-boilerplate:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-microservice-infra-boilerplate
    env_file: .env
    environment:
      NODE_ENV: development
      DB_HOST: db-microservice-infra-boilerplate
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      API_PORT: ${API_PORT}
    depends_on:
      db-microservice-infra-boilerplate:
        condition: service_healthy
    ports:
      - "${API_PORT:-3000}:3000"

volumes:
  db-microservice-infra-boilerplate_data:
